### PR TITLE
add new font

### PR DESCRIPTION
**Pull request by UpTiGamer**

### CODE REVIEW

**Comment by SipSup3314** [comment]
oh wow, my very own 404 page. i was gonna do it, but thanks for that. vercel is currently broken so i can't test it, but ill try copying it to my local clone

**Comment by SipSup3314** [comment]
a few things. the 404 page is perfect and i absolutely love it. on the vm, the buttons straight up don't work, so you might need to fix that. also, the font does not look very clean, so can you get rid of it?. fix those and ill merge

**Review by SipSup3314 — CHANGES_REQUESTED** [review]
remove font and fix vm buttons. 404 page is amazing btw

**Comment by UpTiGamer** [comment]
> a few things. the 404 page is perfect and i absolutely love it. on the vm, the buttons straight up don't work, so you might need to fix that. also, the font does not look very clean, so can you get rid of it?. fix those and ill merge

the buttons work on my end

**Comment by SipSup3314** [comment]
Well, I think we're good now. I'm gonna go ahead and merge this. Thanks for helping, dude :)

**Pull request merged**
